name: Deploy to Firebase Hosting

on:
    push:
        branches:
            - master  # Make sure this matches your branch name

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Set up Firebase credentials
              run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > "$HOME/service-account.json"

            - name: Deploy to Firebase Hosting
              env:
                GOOGLE_APPLICATION_CREDENTIALS: "$HOME/service-account.json"
              run: |
                firebase deploy --only hosting
